[0m13:24:02.411935 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B0CD9C3A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B0CBAE0550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B0CEDC3C50>]}


============================== 13:24:02.416097 | 75e40a99-96ef-419d-8a44-722a61a303cd ==============================
[0m13:24:02.416097 [info ] [MainThread]: Running with dbt=1.10.4
[0m13:24:02.416792 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init .', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:24:24.811573 [debug] [MainThread]: Starter project path: C:\Users\user\Documents\Datasience\telegram-medical-insights\.venv\Lib\site-packages\dbt\include\starter_project
[0m13:24:24.849325 [info ] [MainThread]: 
Your new dbt project "telegram_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m13:24:24.850337 [info ] [MainThread]: Setting up your profile.
[0m13:25:39.955860 [info ] [MainThread]: Profile telegram_dbt written to C:\Users\user\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m13:25:39.957497 [debug] [MainThread]: Command `dbt init` succeeded at 13:25:39.957279 after 97.79 seconds
[0m13:25:39.957995 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B0CFF78E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B0CFE2FBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B0CEC1B790>]}
[0m13:25:39.958815 [debug] [MainThread]: Flushing usage events
[0m13:25:40.932814 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:28:10.689130 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEECC03A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEAD00550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEE007C50>]}


============================== 13:28:10.693300 | 406f7047-bb41-44df-9137-496164c20693 ==============================
[0m13:28:10.693300 [info ] [MainThread]: Running with dbt=1.10.4
[0m13:28:10.693905 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:28:10.694331 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Datasience\telegram-medical-insights\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:28:10.695140 [debug] [MainThread]: Command `dbt run` failed at 13:28:10.695028 after 0.25 seconds
[0m13:28:10.695434 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEE025480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEDEE7770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001FEEDE5BDF0>]}
[0m13:28:10.695753 [debug] [MainThread]: Flushing usage events
[0m13:28:16.659131 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:42:42.848922 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F5A7D3A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F588A0550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F5BBC7C50>]}


============================== 13:42:42.853107 | e5dea96b-4a88-4cfd-81e6-3ac0e821fba7 ==============================
[0m13:42:42.853107 [info ] [MainThread]: Running with dbt=1.10.4
[0m13:42:42.854084 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run --models fct_messages', 'send_anonymous_usage_stats': 'True'}
[0m13:42:42.854415 [warn ] [MainThread]: [[33mWARNING[0m]: Deprecated functionality
Usage of `--models`, `--model`, and `-m` is deprecated in favor of `--select` or
`-s`.
[0m13:42:42.854860 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'deprecation', 'label': 'e5dea96b-4a88-4cfd-81e6-3ac0e821fba7', 'property_': 'warn', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F5BBE5350>]}
[0m13:42:42.855311 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\user\Documents\Datasience\telegram-medical-insights\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:42:42.855851 [warn ] [MainThread]: [[33mWARNING[0m][DeprecationsSummary]: Deprecated functionality
Summary of encountered deprecations:
- ModelParamUsageDeprecation: 1 occurrence
To see all deprecation instances instead of just the first occurrence of each,
run command again with the `--show-all-deprecations` flag. You may also need to
run with `--no-partial-parse` as some deprecations are only encountered during
parsing.
[0m13:42:42.856722 [debug] [MainThread]: Command `dbt run` failed at 13:42:42.856624 after 0.14 seconds
[0m13:42:42.857004 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F5BA1BDF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F5BA1BF00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F5BA7CA50>]}
[0m13:42:42.857320 [debug] [MainThread]: Flushing usage events
[0m13:42:43.836354 [debug] [MainThread]: An error was encountered while trying to flush usage events
